/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tiga_ycsb_YcsbClient */

#ifndef _Included_com_tiga_ycsb_YcsbClient
#define _Included_com_tiga_ycsb_YcsbClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    initClient
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tiga_ycsb_YcsbClient_initClient
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    closeClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tiga_ycsb_YcsbClient_closeClient
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    read
 * Signature: (Ljava/lang/String;Ljava/util/Set;Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_com_tiga_ycsb_YcsbClient_read
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    update
 * Signature: (Ljava/lang/String;Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_com_tiga_ycsb_YcsbClient_update
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_com_tiga_ycsb_YcsbClient_insert
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_tiga_ycsb_YcsbClient
 * Method:    transfer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tiga_ycsb_YcsbClient_transfer
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
